import { readFileSync, readdirSync, statSync } from "node:fs";
import { basename, join, resolve } from "node:path";

/** Preserve dependency notices from the actual bundle inputs, not only runtime dependencies. */
export function bundledLicenses(inputs: string[], root: string): string {
  const packages = new Set<string>();
  for (const input of inputs) {
    const marker = input.lastIndexOf("node_modules/");
    if (marker === -1) continue;
    const parts = input.slice(marker + "node_modules/".length).split("/");
    const count = parts[0]!.startsWith("@") ? 2 : 1;
    packages.add(resolve(root, input.slice(0, marker), "node_modules", ...parts.slice(0, count)));
  }
  return "# Bundled dependency licenses\n\nGenerated by bun run build. Includes license/notice files shipped by bundled packages.\n\n" +
    [...packages].sort().map(directory => {
      const pkg = JSON.parse(readFileSync(join(directory, "package.json"), "utf8")) as { name: string; version: string };
      // These npm tarballs omit their license files; exact-version upstream copies are reviewed.
      const supplements: Record<string, string> = {
        "@alcalzone/ansi-tokenize@0.1.3": "ansi-tokenize-0.1.3.txt",
        "yoga-layout@3.2.1": "yoga-layout-3.2.1.txt",
      };
      const supplement = supplements[`${pkg.name}@${pkg.version}`];
      const files = readdirSync(directory, { recursive: true, encoding: "utf8" })
        .filter(file => !file.split("/").includes("node_modules") && /(?:^|[.-])(license|licence|copying|notice)(?:$|[.-])/i.test(basename(file)))
        .filter(file => statSync(join(directory, file)).isFile()).sort();
      if (!supplement && !files.some(file => /license|licence|copying/i.test(basename(file)))) throw new Error(`No license text found for ${pkg.name}@${pkg.version}`);
      return `## ${pkg.name}@${pkg.version}\n\n` + files.map(file => `### ${file}\n\n${readFileSync(join(directory, file), "utf8")}\n`).join("\n")
        + (supplement ? `\n${readFileSync(join(root, "licenses", supplement), "utf8")}\n` : "");
    }).join("\n");
}
